version: '3'
services:
  neo4j:
    image: neo4j
    env_file:
      - database.env
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - sevetyad-neo4j:/data

volumes:
  sevetyad-neo4j: